### ISSUE TITLE
CMS integration 

### ISSUE THREAD

**Issue by Laazarus** [jovotech/jovo-sample-voice-app-typescript#4]
Hello, 

I am trying to connect a private google spreadsheet into an alexa skill build starting from this example.

I am able to connect the spreadsheet on a "normal" jovo project but on a typescript project I cannot get the cms response. 

I do not get any error but the cms return always the key of the cms, not the values (the speech).
The credentials json are in a credentilas folder and i have written a little command to move them in the dist folder after npm run tsc and before jovo run but still does not work.

Does anyone else had the same problem?

Best Regards

**Comment by aswetlow** [comment]
Hey @Laazarus 
Add this to your `tsconfig.json`:
```json
    ....
    "resolveJsonModule": true
  },
  "include": [
    "src/**/*",
    "test/**/*",
    "src/credentials.json" 
  ],
```
This will add the `src/credentials.json` to the `/dist` folder on `tsc`.

Show me the cms part of your `config.ts`

**Comment by Laazarus** [comment]
Hello, 

Sorry for the delay in my response but has been crazy this week as I had the demo of the skill.

The access of the cms is not a problem if I use the normal javascript, which I have used for the demo, version. The configuration that I am trying in typescript is the same as the one that works in javascript.
here is the config

    cms: {

       GoogleSheetsCMS: {

           spreadsheetId: '1r-97hsRxQfKBY9nUIGStNJISWSylFCp_pfdszsZbCMs',

           credentialsFile:'./credentials/credentials.json',

           access: 'private',

           sheets: [

                {

                    name: 'intro',

                    type: 'Responses',

                    position:1

                },

           ]

       }

      }

When I call the cms i just get the key of the cms ut not the value..

Thanks for the suggestion of the tsconfig.jon It is adding the credentials now but still I cannot get the values from the cms.
:(

**Comment by Laazarus** [comment]
I got it working :)
Stupid me I did not import the credentials in a subfolder but I was looking for it in a subfolder :(

Thanks for your support now I can covert the js skill in ts :+1: 

SSuper Thanks
